### ISSUE TITLE
Path issues prevent use in Rails

### ISSUE THREAD

**Issue by adelevie** [18F/iaa-gem#23]
```
➜  terms git:(master) ✗ bundle exec rails c
Loading development environment (Rails 4.2.2)
irb(main):001:0> IAA
=> IAA
irb(main):002:0> IAA::Form7600A.new
Errno::ENOENT: No such file or directory @ rb_sysopen - lib/mappings/7600A.json
    from /Users/alandelevie/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/iaa-0.1.1/lib/base_form.rb:13:in `read'
    from /Users/alandelevie/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/iaa-0.1.1/lib/base_form.rb:13:in `get_mapper_fields'
```

**Comment by afeld** [comment]
You might try using [`expand_path`](http://ruby-doc.org/core-2.1.5/File.html#method-c-expand_path) to ensure that you are loading files relative to `base_form.rb`.

**Comment by afeld** [comment]
Something like

``` ruby
def get_mapper_fields(path)
  full_path = File.expand_path(path, __FILE__)
  JSON.parse(File.read(full_path))
end
```

**Comment by adelevie** [comment]
Close:

```
Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/alandelevie/terms/lib/mappings/7600B.json
```

`terms` is the Rails app. I need it to point instead to the gem path.

**Comment by afeld** [comment]
Figured this out, yeah?

**Comment by monfresh** [comment]
In [self.mapper_path](https://github.com/18F/iaa-gem/blob/master/lib/base_form.rb#L72), try this:

``` ruby
"#{File.dirname(__FILE__)}/mappings/#{self.form_name}.json"
```

and place `base_form.rb` and the `mappings` folder inside the `iaa` folder. It's considered a best practice to place all your files inside the folder that has your gem's name, as explained here: http://guides.rubygems.org/patterns/#respect-the-global-load-path

**Comment by adelevie** [comment]
https://github.com/18F/iaa-gem/pull/24
